### PR TITLE
Replace 2016 designed based site to 2017 test site.

### PR DESCRIPTION
**Pull request by KMR-zoar**
Thank you for preparing the repository for 2017.

### CODE REVIEW

**Comment by RobJN** [comment]
Hi @KMR-zoar. Welcome to State of the Map 2017 github.

If you have seen your emails you will have read that this edit is much bigger than we were expecting. If this was due to poor communication then please accept my apologies.

It looks like you have built the new site using the same system (Jekyll) - it is great that you are happy using this. However, the big change in design was unexpected. For example the removal of much of the CSS and the secondary pages (e.g. [program/index.md](https://github.com/openstreetmap/stateofthemap-2017/pull/13/files#diff-6d7b2dce3cd524e8408eb404d8d73066)).

My concern is that this may make it harder to add new pages based on last years code (such as the [conference program](https://github.com/openstreetmap/stateofthemap-2016/tree/gh-pages/program)). We would need your ongoing support with styling (CSS) and so on.

This may be me worrying too much -> I am not a web developer so I do not know it is now harder to use code from [last years site](https://github.com/openstreetmap/stateofthemap-2016) or just as easy. 

To help I have a few questions: 

1. How much ongoing support are you able to provide?
2. How easy is it to use parts of last years code in this new site?

**Comment by KMR-zoar** [comment]
First, I'm not good at English.
I'm not going to any harm you. You should have sent me a message. Because you are also careful about us and SotM2017.

I must apologize. about my editing surprised you, even if poor communication is the cause.

Your concern is plausible. There is no objection about revert, written by email.

Thanks for letting us know the crisis.

By the way, Thanks for invited to the OSMF on Slack. But I couldn't find the channel for the SotM 2017. I thought there was a dediceted channel.

**Comment by RobJN** [comment]
@KMR-zoar Your English is much better than my Japanese (I cheat and use Google Translate).

Yes, I should have sent you an email explaining what we wanted. I assumed Kinya (ikiya) had done this, but he probably assumed I had!! I will open "issues" here in GitHub so that you know.

I have now added you to the SotM 2017 channel in slack.

**Comment by KMR-zoar** [comment]
Thank you for helping me with so many things!

**Pull request merged**
