### PR TITLE
Site cleanup and polish

### PR DESCRIPTION
**Pull request by tristen**
This PR does the following:

- Creates a uniform color palette across section backgrounds and elements. Ref #18
- Simplify type treatments by sticking to two weights of Work Sans. Made
site wide adjustments to type scale.
- Simplify the navigation. drop animation and use a background fill that
works accross pages. Ref #20
- Tinted the background splash on the front page to give the logo
a stronger contrast. Also adjusted the colors in the logo to fit better
with the color theme and build a stronger relationship between the icon
mark + words. Ref #15
- General cleanup. Removed a bunch of things belonging to its original
boilerplate that wont be used here. Cleaned up DOM structure through
most sections.

sotm-refresh

cc @mikelmaron

### CODE REVIEW

**Comment by ikiya** [comment]
We want to make the color of the logo the same color as the Logo Design concept.
Logo Design Concept
https://github.com/osmfoundation/sotm2017/issues/7#issuecomment-266302784

**Comment by ikiya** [comment]
tcul

**Comment by ikiya** [comment]
And There are four seasons in Japan. 
Ultimately we want the picture of the background castle to dynamically change the four seasons.
test

**Comment by RobJN** [comment]
Discussion seems to have moved here: https://github.com/osmfoundation/sotm2017/issues/6

I added @tristen to that repo so that he can read it. But in summary, although this darker theme is great, it seems like the local preference is to use a light theme this year. They are going to make some changes based on what we have live at the moment. I will review this PR to see if there are some changes that we should keep (I don't want good work to go to waste).

**Comment by RobJN** [comment]
Oh and dynamic changes according to the season are a "no", but we will use these images in future blog posts :-D

**Comment by mikelmaron** [comment]
@RobJN let's see if we can pick out the general clean up, font changes, and nav fixes

**Comment by Firefishy** [comment]
Closing as stale.

**Pull request closed without merging**
