### PR TITLE
Add "Scholarship" into nav and link to Call for Proposals into program page. And edit link to newsletter.

### PR DESCRIPTION
**Pull request by KMR-zoar**
Starting call for scholarship and call for proposals.
Edited link that from "sign up for event updates" to newsletter section. Until now only link to head of index.html.

https://github.com/openstreetmap/stateofthemap-2017/issues/26
issue #26

### CODE REVIEW

**Comment by mikelmaron** [comment]
@KMR-zoar can you also link the "Scholarships" text in the footer?

Also think we need a wide section on the home page announcing both?

We also need someone to quickly adjust the text on the /program page. There is now a link to the CfP but the rest of the text doesn't make sense. @RobJN?

**Comment by KMR-zoar** [comment]
I was forgot footer, complecately. Thanks.

I edited link to CfP by program too. linked directly from "program" letters to CfP.
It seems like I made a mistake in the meaning of English.

Pushed branch again.

**Comment by RobJN** [comment]
Merged.

> Also think we need a wide section on the home page announcing both?

I think so too. @KMR-zoar Can you add such a block to the home page?

**Comment by KMR-zoar** [comment]
@RobJN I added an annoucing both on the homepage. pull #32

**Pull request merged**
